user:
    path: /user
    controller: App\Controller\UserController::index
product:
    path: /product
    controller: App\Controller\ProductController::index
order:
    path: /order
    controller: App\Controller\OrderController::index