<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMFUDNDl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMFUDNDl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMFUDNDl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMFUDNDl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMFUDNDl\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'MFUDNDl',
    'container.build_id' => 'b6826927',
    'container.build_time' => 1549026985,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMFUDNDl');
